---
- hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: no

    - name: Copy Volcanix website
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Restart nginx
      service:
       name: nginx
       state: restarted
       enabled: yes
